/*#include<bits/stdc++.h>
using namespace std;
int main(){
    char n;
    cin>>n;
    n=n-'a'+'A';
    cout<<n;
}*/

/*
                                                                                                                                                                                                                                                                                                            
                                                                                                             +.;._.I.-.I.-.I.-.l.?.!.?.l.].!.].!.].!.].!.].i.].i.].i.].i.].i.-    .>.[.i.[.i.[.i.[.i.[.i.[.i.[.i.[.                                                                                         
                                                                                                            ]./.[.t.}.f.}.f.{.j.1.j.{.j.{.j.1.r.1.j.{.r.1.r.).r.).r.).r.).r.).n.     .x.).x.).x.).x.).x.).x.).x.1.j.).j                                                                                     
                                                                                                          .  `.i.^.>.".<.".<.,.~.,.~.,.<.,.~.:.~.:.~.:.~.:.+.:.+.:.+.:.+.:._.          _.;._.;._.;._.;._.;._.:.~.:.+.:.~.:.                                                                                 
                                                                                                             .).x.(.n.|.n.|.u.|.u.|.u'\.u'\.u'\.v'\.v'\.v'/.v`/.v`/.v`/.c^             .c^/.c^/.c^/.c^/.c^/.c`/.c`\.v`/.v`/.v.                                                                              
                                                                                                          .:.+.I._.I.-.I.-.I.?.l.?.l.?.l.?.l.?.!.].!.].!.].i.].i.].i.].!.[        .!.[.i.[.i.[.i.[.i.[.i.[.i.[.i.].!.].i.].!.].i.                                                                           
                                                                                                         ./.]./.[.t.}.f.}.f.{.j.{.j.{.j.{.j.{.j.1.r.1.r.1.r.).r.).r.1.r.).r.{    .n.).x.).x.).x.).x.).x.).x.).r.).r.1.r.1.r.1.r.1.j                                                                         
                                                                                                      .!.`.i.`.i.^.>.".<.".<.,.<.,.<.,.~.,.~.,.~.:.~.:.~.:.+.:.+.:.+.:.+.:.+.;.+    .I._.;._.;._.;._.;._.;._.;.+.:.+.:.+.:.+.:.+.:.~.,                                                                      
                                                                                                         .).x.).x.(.x.(.n.|.n.|.u.|.u'\.u'\.u'\.u'\.u'\.v'/.v`/.v`/.v`/.v`/.c^t.c^/    .c`/.c^/.c^/.c^/.c^/.c`/.c`/.c`/.v`/.v`/.v'\.u'/.n                                                                   
                                                                                                         +.;._.I.-.I._.I.-.I.-.I.?.l.?.l.?.l.?.l.?.!.].!.].i.].i.].i.].i.[.i.[.i.[.>._   ?.i.[.i.[.i.[.i.[.i.[.i.[.i.].i.].i.].i.].!.].i.].                                                                 
                                                                                                         ./.[.t.}.f.}.t.}.f.}.f.{.j.{.j.{.j.{.j.{.j.1.r.1.r.).r.).r.).r.).x.).x.).x.).n.   .|.x.).x.).x.).x.).x.).x.).r.).r.).r.1.r.1.r.1.r.1                                                               
                                                                                                  .!.  !.`.i.^.>.^.>.^.>.".<.".<.,.~.,.~.,.~.,.~.,.~.:.~.:.+.:.+.:.+.:.+.;._.;._.I.+.:._.;   ,.-.I._.I.-.I._.;._.;._.;._.;._.;._.:.+.:.~.:.+.:.                                                             
                                                                                                  1.    r.).x.(.x.(.x.(.n.|.n.|.u.|.u'\.u'\.u.|.u'\.v'\.v'/.v'/.v`/.v`/.v^/.c^/.c^/.c`/.c^t. ./.z"t.z^t.X"t.c^t.c^/.c^t.c^t.c^t.c`/.c`/.v`/.c`/.v                                                           
                                                                                               :. .:. .:.+.;._.I._.I.-.I.-.I.?.l.?.l.?.l.?.l.?.!.].!.].!.].!.].i.].i.].i.].i.].i.[.i.[.>.[.>.}.i.[.i.[.>.}.<.}.>.[.>.}.<.[.i.[.i.[.i.}.>.[.i.[.i.[.                                                         
                                                                                                  /.] /.[./.[.t.}.t.}.f.}.f.}.f.{.j.{.j.{.j.{.j.1.j.1.r.1.r.1.r.).r.).r.).r.).r.).x.).x.).x.]   1  .).x.(.n.(.x.(.x.(.n.|.x.).x.).x.(.n.(.n.).    f.{                                                       
                                                                                               !.`.!. .i.`.i.^.>.^.>.".<.".<.^.>.,.<.,.<.,.~.,.~.,.~.:.~.:.~.:.+.:.+.:.+.:.+.:.+.;._.;.+.         ._.;._.;._.;._.I._.I.-.I.-.I.-.I.-.I.-.I._.;.+     :                                                      
                                                                                               .r.1.r ).r.).x.(.n.(.x.).n.(.x.(.u.|.u.|.u'\.u'\.u'\.v'\.v'\.v'/.v`/.v`/.v`/.v`/.c^/.c'         .v^f.c^t.c^t.c^/.z^t.z^f.X"f.X"f.X"f.z"t.z^t.z^t.z"t         x                                               
                                                                                               :.+.:.+.;.+.;._.I._.:    .-.I.-.l.?.l.?.l.?.l.?.l.?.!.].!.].!.].!.].!.].i.].i.].i.[.           .>.[.i.[.i.[.<.}.>.[.>.}.<.}.<.}.<.}.<.}.<.}.<.}.<.}.>.]                                                      
                                                                                               .]./.] /.]./.[.t.}.    f.}.f.}.f.{.f.{.j.{.j.{.j.{.j.1.r.1.r.1.r.1.r.1.r.).r.).r.}            .n.).x.).x.).n.|.x.(.x.(.n.|.n.|.n.|.n.|.n.|.n.|.n.|.n.(.n.                                                    
                                                                                               !.`.!. .i.`.i.^.i    .".i.^.<.".<.".<.,.<.,.~.,.~.,.~.:.~.:.~.:.~.:.~.:.+.:.+.:.~            .I._.;._.;._.;.-.I._.I.?.I.?.l.?.l.?.l.?.l.?.l.?.l.-.I._.I._.;.                                                 
                                                                                                r.1  .).x.)   )    .n.(.n.|.n.(.n.|.u.|.u'\.u'\.u'\.v'\.v'\.u'\.v'\.v`/.v`/.v'/.v`\.r          .c^/.c`t.c^t.z^t.c^f.X"f.X"f.X,j.X,j.X,j.X,j.X,j.z"f.z"f.c^f.v                                               
                                                                                               :.     .;.        +.I.-.I.-.I.-.I.?.l.?.l.?.l.?.l.?.l.?.!.].!.].i.].i.].i.].i.].!.[.i.].i.].!.     .i.[.i.[.>.[.>.[.>.[.<.{.<.{.<.{.~.{.<.{.<.{.<.{.<.}.>.[.>.}.                                             
                                                                                                ]  . ./.        }.t.}.f.}.f.}.f.{.f.{.j.{.j.{.j.{.f.{.r.1.r.1.r.).r.).r.).r.).r.).x.).x.).x.).x.     .x.).x.).x.(.x.(.n.|.u.|.u.|.u'|.u.|.u.|.u.|.u.(.n.(.x.|.n.                                            
                                                                                                  .!  .       .>.".<.".<.".<.".<.".<.,.<.,.~.,.~.,.~.:.~.:.~.:.+.:.+.:.+.:.+.:.+.;._.;._.;._.;._.;.     .;._.I.-.I._.I.?.l.?.l.?.!.?.!.?.!.?.!.?.!.?.l.?.l.?.I._.;                                          
                                                                                                             .(.n.|.n.|.n.|.n.|.n.|.u.|.u'|.u'\.u'\.v'\.v'\.v'/.v`/.v`/.v`/.v`/.v^/.c^/.c^/.c`/.v`t.z.    \.z^t.z"t.z^f.X"f.X"f.X,j.X,j.Y,j.Y,j.Y,j.X"f.X,f.z^t.z"f.                                        
                                                                                             +  .           ._.I._.I.-.I.-.I.-.I.-.I.-.l.?.l.?.l.?.!.].!.].!.].i.].i.].i.].i.].i.[.i.[.i.?.>.[.i.[.>.[.>.    [.>.}.<.[.>.}.<.{.<.{.<.{.~.{.~.{.~.{.~.{.<.{.<.{.>.[.>.                                       
                                                                                           .   .    ]      .[.t.[.t.}.f.}.f.}.t.}.f.{.j.{.j.{.j.{.j.1.r.{.r.1.r.).r.).r.1.x.1.r.).x.).x.}  .).x.(.x.(.n.).x   f.(.x.(.x.(.u.|.u.|.u.|.u'\.u'\.u'\.u'\.u.|.u.|.n.(.n.(./                                     
                                                                                           !   !   >.     .i.".>.^.>.".<.".<.".<.,.<.,.~.,.~.,.~.,.~.:.~.:.+.:.+.:.+.:.+.:.i ^.+.:.+.:.+.^   ;.+.;._.;.+.;._.   .I.-.I._.I.?.l.?.l.?.l.?.l.?.!.?.!.?.l.?.l.-.l._.I.-.I.>                                    
                                                                                           .      ).     .(.n.(.x.(.n.|.n.|.n.|.u.|.u'|.u.|.u'|.u'\.v'\.v'/.v`/.v`/.v`/.v^t.  (.c`/.v`/.v`|   t.c`t.c^/.c`t.c^/   /.z^t.z"f.X,f.X,j.Y,j.Y,j.Y,j.Y,j.Y,j.Y,j.X,f.z^f.z"t.v                                   
                                                                                            .    +.:    ._.I._.I.-.I.-.I.-.I.?.l.?.l.?.l.?.l.?.l.?.!.].!.].i.].i.].i.].i.[.i   !.[.i.].!.[.i   >.[.i.[.>.[.i.}.>.   .}.>.}.<.{.<.{.~.{.~.{.~.{.~.{.~.{.~.{.~.{.>.}.>.}.>.]                                  
                                                                                                  /.    [.t.}.t.}.f.}.f.}.f.{.j.{.j.{.j.1.j.1.j.1.j.1.r.1.r.).r.).r.).r.1.x.}  .).x.).r.).x.{  .(.x.).x.[            .x.(.u.|.u'|.u'|.u'\.u'\.u'\.u'\.u'\.u'\.u.|.n.(.x.(.x                                 
                                                                                                .      i.`.>.".<.".<.".<.".<.,.~.,.<.,.~.,.~.,.~.,.~.,.+.:.~.:.+.;.+.:.+.;._.   .;.+.;._.;._.,  .;.                    _.I.-.l.-.l.?.l.?.l.?.!.?.!.?.!.?.!.?.l.?.l.-.l._.I._                                
c^t.X,f.z^/.u.)                                                                                .r.1    .x.).n.|.n.|.n.|.n.|.u'|.u'|.u'\.v'\.v'\.v`\.v`/.c`/.c`/.v`/.c^/.c^t.z.  c"t.z^t.c^t.c^(                      ./.z"t.X,f.X,f.X,j.Y,j.Y,j.Y:r.Y:r.Y:j.Y,j.X,j.X"f.z"t.c                               
.r.).n.(.x.1./.~.].:                                                                           ; +.    :._.;.-.I.-.I.+.I.-.I.?.l.?.l.?.!.?.!.?.!.].!.].i.[.i.[.i.}.>.[.>.[.i.[  .}.>.}.>.}.>.}.;                .].i.[.>.}.<.{.<.{.<.{.~.{.~.{.~.1.~.1.~.1.~.{.~.{.<.}.<.}.>.]                              
O_%n#18\q~h[LIm>u.z'1.                                                                     .   .  /    .[.t.[.f.}.    f.}.j.}.j.{.j.{.j.1.r.1.r.).r.).x.(.n.(.n.(.n.(.n.).x.(.   .x.|.n.|.n.|.n.             .n.(.x.(.x.(.u.|.u.|.u.|.u'\.u'\.u'\.v'\.v'\.v'\.u'\.u.|.n.(.n.(.r                             
v$Q$v$Q$v$C$)O!c.{.(.I.>                                                                       !  .    >.".>.^.>.    ".<.,.<.,.~.,.~.,.+.:.+.:.+.:._.;._.I._.I._.I.-.I._.I._.I.  l.-.I.-.I.-.I._.         .-.;._.I._.I._.I.?.l.?.l.?.l.?.l.?.l.].!.].!.].!.].!.].l.?.l.-.I.-.I.~                            
$B$o$B$o$B$o$B$U$|QIOlj.n.                                                               .1    .x.)    .x.(.n.|.n   u.|.u'\.u'\.u'/.v`/.c`/.c`/.c`t.z^f.z"f.z"f.z"f.z"f.z^t.z^/  "f.z"f.z"f.z"f.z.      v^t.z"f.z"t.z^t.z"f.X,f.X,f.X,j.Y,j.Y:r.Y:r.Y:r.Y:r.Y:r.Y:j.Y,f.X"f.X"f.x                           
m$Y$m$Y$m$Y$m$v$Xd.\.t.~.-                                                                     ;.+.    I._.I.-.;   l.-.l.?.!.?.!.?.!.].i.[.>.[.i.[.>.[.>.}.<.}.<.}.<.}.<.}.<.{.  [.<.}.<.}.>.}.<.[        .<.}.>.}.>.}.>.}.<.{.<.{.<.{.<.{.~.{.~.1.~.1.~.1.~.1.~.1.~.{.<.{.<.}.>.                           
$d$W$d$W$d$W$m$Uh<p~c.X'(                                                                      .[./    .[.t.}.t   t.{.j.{.j.{.j.1.r.).r.).r.(.n.(.n.(.n.(.n.|.n.|.n.|.n.(.u.|.n  .u.|.n.|.n.|.n.(.f        .(.n.|.n.|.x.(.u.|.u.|.u.|.u.|.u'\.u'\.v'\.v'\.v'\.v'\.u'\.u.|.u.|.n.|.                          
f@L$v$Q$u$X$[w-0./.f.+.?.                                                                      > `.    >.^.>.".   .~.,.<.,.~.,.~.:.+.;.+.;._.I._.I.-.I.+.;._.I.-.I.-.I.-.I.?.l.  ^.?.I.-.I.-.I.-.l.          ;.-.I.-.I._.I.?.l.?.l.?.l.?.l.?.l.?.!.].!.].!.?.!.].!.?.!.?.l.?.l.-.l                          
$b$m$*$m$b$X$z#[*}C:0lr.                                                                   .   .r.(.   .x.(.n.   .|.n.|.u'\.u'\.v`/.v`t.v`t.z^t.c^  v"t.z^t.z"f.z"j.X,j.X,f.X,j   r.X"f.X"j.X,j.X,j.          t.z"f.X"t.z"f.X,f.X,f.X,f.X,j.X,j.Y:r.Y:r.Y:r.Y:r.Y:r.Y,j.Y,j.X"f.X"/                         
)W{*x$)atM~Q+Q.f.r.?.{.                                                                        ;._.    ;._.;.+  .?.l.[.>.{.~.{.~.).+.(._.\.?.\.?./  ./.+.1.<.}.<.{.<.}.>.}.<.{.:  .<.{.<.{.<.{.<.{.<         [.<.}.<.}.>.}.<.{.<.{.<.{.<.{.<.  :.{.~.1.~.1.~.).~.1.+.1.~.1.~.{.<.{.                         
p}@x*)@jb-o[C:0lr.n.}.                                                                    /.   'f.O+t t?CIp?Q. (o1Bx*($uM\$cW/$c&/$z%j$?uj$X%j$YBr# dx$zW\$ra}W\d_a}Q!p_Y"0ln.U.  c'|.u.|.n.|.u.|.u.)      .\.x.(.u'|.n.|.u.|.u.|.u.|.u.|.u.\.    u`\.v'\.v`t.c`/.v`/.v`/.v'\.v'\.n.                        
.(`z./`u.{.(.>.-.".                                                               .-.+.r.xim. .b!Q?k. .w>0]k; .h>0[biQ[k<O}h>0}h<Z{h<O{v U1h<Z{a~m< .m1o~m1o~m1*_w)o~w)*_q)*+m)Q f]Z^n,c.(.\._.}.!.-.      <      .-.l.-.l.?.l.?.l.?.l.?.l.?.!.    >.!.].!.[.i.[.i.].!.].!.?.l.?.l.-.                       
Clv`Q!v.J,f.u.                                                                xiMr&j$Y%j$Y%jB )x$YBj@  ?$U$rk #n$J$x$U@x$J$n$J$n$C$n$C$1 }$u$C$u$QB QL$v$L$v$Q$c$0$c$Q$c$0$c$Q$\ \$z$0$c$O$z$Q$n$z#]h<  c   u~   ,f.X"j.X,f.X"f.X,f.X,f.X,j.X,t      ,j.Y:r.J;x.J;x.U;r.U:j.Y,j.Y,j.z                       
.-.I.-.I.                                                                  j>O.nIY.\.x.{.t.-.  +.).+.   .j.t  'xlQ^X~wIC?bi0{a+w|#-p|#?m {]d\M?p|W] .W]d\W]d\W]b/W]b/W]b/W]b/&}Q z{k/&[b/W]b/&[b/W]kfW.   ;a-         .<.{.<.{.<.{.<.{.<.{.<.{.       .~.).+.1._.).+.)._.u.).1.~.{.<.+                      
                                                                                                [./.]    ./   t [.f.[.t.}.j.).c:u^w[m-&f  $X%f$YBr$ {x$U@r$YBr$U@r$U@r$U@r$U@x$f .$J$x$U@x$J$x$X$x$J$x%  |$L$t&>       .}.x.(.u.|.u.|.u.|.u.|.u.       `/.v`/.v^t.c`/.clhu$L%]m,/.u'|.                      
                                                                                                .` !.    `.   .i.^.>.".>.".<.,.<.,.~.,.+  .?.>./.j>  X>mlL[h<Z1o+w)o+m)o+m1o+w)Z l(*_q(*+w)*_q. iw)o+w){ n(#?O.                >.l.-.l.-.l.?.l.?.      i.i.].!.[.i.].i.|"p|#?p|*,{.?.l.                     
                                                                                                    r        .).x.(.n.(.u.|.u'\.v`/.v`/.  1.v`/.c^t  `\.v^t.Jlc:p[w{$J$v$0$c$Q$|  $z$0$z$0$c$Op nC$c$0$) +$X$Z$\Z   c:r.Y:r.z    ^f.X,f.X"f.X:x.X       v;r.UIqx$\U.U;r'&0$Y$Z$X$Z8lY,f                     
                                                                                                 _  .        -.;._.I.-.I.-.I.?.l.?.!.].    >.].>.[.  [.>.}.>.}.>.[.!.}._.j.f;0Iu  -d\W]b/&[b/8~  t]k/8}w  >hfB[)      .~.{.<.{.<.{.<.{.<.{.<.0]q!1       [.+.).x|%{b>f.+^*{aj%{hf%}k]x.                     
                                                                                                      /      .t.}.f.}.f.}.f.{.j.1.j.).j    .).r.).x  .x.).n.(.n.|.n.(.n.(.n.|.n.   '\.z:v:d)h/$.  kU$n$Cx oL$u$CZ  .).v'\.v'\.    /.|.n.|.u.t<$C$|v       u`/.c`Xt$L$x$<r-$L$u$C$u$C$x8,                    
                                                                                                     `       ^.>.".>.".<.".<.,.<.,.~.:     _.:.+.;.  ;._.I._.;._.I._.I.-.l.?.l.    [.!.?.!.-.l.    ?.1^Q. .o?d|#?n  .i.?.!.?.!.].    ".?.l.?.i.d-p"       .[.i.].-?M-p|o.(-M?p|#-p(*_q\d.                   
                                                                                                            x.(.n.(.n.|.n.|.n.(.u.|.u   Q  .v'\.v`\  `/.c^/.c`/.z^t.z^t.c^f.X,j    .Y,j.X,j.Y:r  ,  z,j.X |x$Z$X$[   "r.Y,j.Y:r.U:j.    z,j.X"t.q1z        .Y:r.U:c\$O$Y$O$X$Z$X$Z$X$O$Xk                   
                                    ,t                                                             :         _.I._.I.-.I.-.I.-.I.-.!.  _.  !.?.l.?.  ?.i.[.i.].>.}.>.[.i.}.<.{.  ? >.{.<.{.~.1.l {.  1._.  QrB{hrb   {.~.{.~.1.~.{.~.{.    <.{.<.}.!        .1.+.)._lW}hj%{hf8{hf%{hf%{o[                   
                                   <O.  C"                                                                   ./.[.t.[./.[.f.}.t.}.f.   Ix  .1.j.1.f  .r.1.r.).r.(.n.(.n.(.n.(.j  . .|.n.\.u.\.c. .J  .v'\  ?$u$C$u#  .v'\.v'\.v'\.v'\.u.(    .u.|.u'        |.c`/.v`tI$C$u$C$n$C$u$L$n$C%.                  
                                .  r.  (.{                                                             !.`    .i.^.i.`.i.^.>.^.>.".   .\.  <.,.~.:.  ,.~.:.+.:.+.:.+.;._.I._.;.  i  .l.?.!.?.!.~ ,.  ".].: <~p|M?p|L  .].!.].!.?.!.?.l.?.l.i   _.I.?.        !.].!.].<.a]p|#-p|#-p|#?p|M-?                  
                               >h  `#` i*"                                                                       . .x.).r.).x.(.x.(   c,Q  .u.|.u')  '/.v'\.v'/.v`/.c`/.z^t.z"  J>  z,j.X,j.Y,r.  Q.  f.Y,  $Z$Y$Z$Y$. .Y:r.Y,j.X,f.X"f.z"f.X.   ^j.Y        "x.U;r.U:xi$Z$X$O$X$Z$X$O$X$)                  
                              .x:1   ?.r`                                                                        + :._.;.+.:.+.;._   1.}.  I.-.l.-   _.!.?.l.].!.].i.?.i.[.<.]  .r  .{.<.{.<.{.<  .1  .+.1  -@{aj%{hj#. .1.~.{.~.{.<.}.<.}.>.{.    <.?       _.+.1.+.)._.d}hf8{O+8{hf8}hjm                  
                              z[Q.    j+                                                                           .].t.[.t.[./.}.   .U;u  .}.f.{.   .j.{.j.1.j.1.r.1.r.1.x.(   c"  ).n.|.u.|.v'  0~1  '/.  0v$C$u$C$v$+  x'\.v'\.v'|.u.|.n.(.n.)   1.        u'\.v'\.c`/^BC$u$|r<$L$u$L$1                  
                               v.     .                                                                             .`.i.^.>.".i.   ._.(.  >.^.<.,    .<.".~.,.~.:.~.,.~.:._.   .}  .I.-.l.-.l.]  .r.  -.i  .d|#-p\M?p\M,    ,.].!.?.l.?.I.-.I._.l.           .].!.?.i.[.>.C_b1u.>'k-p|M?0                  
                                  )   C.                                                                            r.).r.).x.).x   0iz^O  .n.(.n.    (.n.|.u.\.v'\.v'\.u'/.u  ,w_  u"t.z"f.X,j.  Xlw  .U;  Lm$X$Z$Y$Z$z$0U    .Y:j.X,j.X"f.z"f.z"f.           .Y:r.Y:r.U;r.p/Z`JIn,%Q$X$0j                 
                                .J.f"Y./                                                                            .+.:.+.;._.;.  \.t.}.  I.-.I.-    .l.-.l.?.l.?.!.?.!.].>  .z.x  .}.>.}.<.}.+  ./.   .1  .B{aj%{aj%{hj@)J     _.~.{.<.}.<.}.>.}.>._         <.1.+.1.+.).+.)._.).-.x:bx%.                 
                                Lim  `b]                                                                       .      /.]./.].t.  xrQ.U;r  .}.f.}.    f.}.j.{.j.{.j.1.j.{.r.  oxX^f [.n.|.n.|.u`  Y+Y.  /.  {v$L$u$L$u$C$~         .|.n.|.n.|.n.).x.(.x        .|.v`/.c`/.c^t.z^t.z"f.Xidrp                 
                                ./.  !`n                                                                                .`.i.`.!  'h.-.).  <.^.>."    .>.".<.".~.,.~.,.~.:.  !]d.[. .I.-.I.-.I.]  .n.>  .>  .b\M?d\M?p\M[Q  .        :.?.I.-.I._.;._.I._        .l.?.!.[.i.[.i.}.i.{.<.}.}._}$L$v$L$v$Q$v$Q$
                                n`                                                                              r      . . .r )   Mc$-c`C  .n.(.n     |.n.|.n.|.u'|.n'\.u'|  x$na_f  "t.z"f.z"f.  h_di  YI  Lw$Y$Z$Y$Z$u&x8  `x.c      .X"f.c^t.c^t.v^t.v       X"j.Y:r.Y:r.U;x.JIn.Clu.L!  $B$o$B$o$B$o$B$o
                                                                                                                        .   .+.  {-b{c.[.  I._.I.     .I.-.I.-.l.-.l.?.l.?  .#[pIr.  }.>.}.<.{.+  >X`j  .(  '@{aj%{aj%{h.     ._.(.;     }.>.[.i.[.i.[.>.       .}.~.1.~.1.+.)._.(.-.|.-.\  j$X$Z$Y$m$Y$m$Y$
                                  q.    )                                                                                 /.     ;$XMIU;\  .[.t.[     j.}.f.}.f.}.f.{.j.1.  kx$XZ`t  .x.(.n.|.u'  $tU`  |.  dc$L$u$L$n$L$|  ).u`/.v`/.    x.|.n.|.n.(.n.(.      (.u.|.v'\.v`/.c`/.X,f.Y:j.  @q$o$w$*$q$#$q$#
                                 )`f  .v.                                                                  {          .   .i     c{hl|.(.  >.^.<      .>.".<.".<.".<.,.~.  t~w(o.]   l.-.I.-.I.? <(d.-  .!  ld|M?d\M?p|M?b|- ,.[.i.].!.+    .I.-.I.-.I.-.:      .l.?.l.?.!.].i.[.>.}.<.{.~  iBz$j%X$f%X$jBY$
                                 im>c"O+a                                                                  _                r.  xY$n$1c`   .n.).      |.n.(.n.(.n.|.u'|.n  |$Q$u&~  r"t.z"f.X,r. ?$r#>  X;  $Z$X$Z$X$Z$Y$m$XO  .U;r.U:j.X^   .f.c^t.z^t.z^      u"f.X,j.Y:j.U;r.UIn.Clu.Li  $o$m$o$w$*$w$*$q
                                 _.r,Y.r.                                                 .               .L  .:                .#-q1U.[   ;._.   .  _     I.-.I.-.l.?.!  .p\M?b>r  .}.>.}.<.1.  C{d</  .} -fB{ajB{ajB{ajB{atC  .).+.1.~.}    .>.[.>.}.>.}.     .}.<.}.<.{.~.1.+.(.-.|.?.\  ?$/&c$t&c$t8z$f%
                               -U   f!d[                                                  0               Zr              t     mr$zWiC"   .[.t   n  .f        .}.f.{.r.  $UBj$Uq'  [.n.(.n.|.u  )$Yb.  /. _$u$L$u$L$u$L$u$L$uo  .c`\.u'|.t  .n.).x.).r.).j      .n.|.u.|.v`\.c^t.z^t.z"j.  kz$O$X$Z$z$O$Y$w
                              .u.    {"_                             `                    ^>                      .         .   .O{kit.[   >.^.  ^.  ^.<   +         ^.  f(o~Z)a`[  .l.-.I.-.l.  m\#"l  .  C-d\M?d\M?d\M?d\M?d\L  .].l.?.l.+   _.I._.;.+.I.      I.-.I.-.!.?.!.].>.}.>.{.+  `k\M]b/W[k/&}hjB
                              m~p    }j                              ^\                   ki                            x.        wx$(z.  (.r.   !   .).n    .|.x.         :8z$c@_  c,t.z^f.X"/ mZ$z$'  X  x$Z$Y$Z$Y$Z$Y$Z$X$Z$X*  .Y,j.X"f.c   c"f.c`/.c`/      "f.z"j.X,j.Y;r.JIx.JIu'Ll  BO$z$Z$z$0$X$m$J
                                .z.("U.                              ].                                             .+.;._.         .u.:  .;._   t   -.I.-.      _.!.[                .i.{.<.1  ]B}b-  ;. .br%{ajB{ajB{ajB{hfq.z}/  .1.<.{.<.}    .>.].>.].      }.<.}.<.{.<.1._.)._.(.-.\  +&]d\W[kt&[kt&}a
                                v"v;Cld.                             .x.                  OjC              )q   ]. .]./ ]./.   +X         j.[   u.   .t.}.f.}./                                ;$u$Qb  .  aC$u$L$u$L$u$L$u$C$fj     1.u.\.u.(.x     {.r.).r.     .n.(.n.(.u.|.v`/.c^t.z"j.  df$c&t$z%f$XBj$J
                               ]."  .|'r                             ;.+                  .p!_            .b<j   `.i    .`.>  .k<Z-C.          [.:   ".<.".<.".<.,.~   ?.+.                       .\.     _#?p\M?d\M?d\M?p|M-q]~  .[.!.?.l.-.I._      .+.:.>     ;._.I.-.I.?.l.].i.].i.}.>  `0]d!Q]di0}h<Z{a
                               lk   v{Z>                            r^/.c         L       ||$n            xj$v            1.  cx$J$n%+|         X   n.(.n.(.n.|.u'|.  Mz$L$u$L$z&   u.)        _h+z       Lx$m$Y$Z$Y$Z$Y$Z$Y$Z$nQ  .U,j.X,f.z"t.z.     .c`/.     ^t.z^f.z"f.X,j.Y;r.U:r.CI  @U8f$X%f$X%j$U@n
                               (.     .                             .].i.-        .v       X1a.           .O(a.           .I  .q)o_w!j  .-.    ).   .-.I.-.I.-.l.?.  m?d\W]d\M?b;  >.}.>.}.>  !hf8[)  .  x.  t>hjB{aj%{aj%{af%{afU  .1.~.{.<.}.>.[.      [.!     [.>.}.<.[.>.{.~.1.+.)._.(  _aiQ[bi0[b>O1h~w
                                                                    ).x.).        Quf      ?M\$.           t&tb         ]./.  oX&t$uL.  [.t.  &r|  .}.f.}.f.}.f.{.  Lr$X%j$YBj$J|  .).x.(.n  +$U@r8  .  hu$C@{*v$u$L$u$L$u$C$u$C$u&  .v'|.n.|.n.).x.      j.     .x.).x.|.n.|.u.\.x'/.c^f. .k(8fa1Bro1@x#($v
                                                                    .;.+.;._      .d";     ]:L?Z           CiQ+   .  `.!.`.i  >h>0}m.   .".  ]{0   >.".<.".<.".<.  x+Z{a~m1a~m)k  ._.:._.I  .w(*+Z.    r+p(#?p|#-p\M?d\M?p|M-d\W-w|d  .].l.-.I._.:.+.      i.   .;.+.;.-.I.-.I.?., i.i.[.l ?,Yi0"z<Z,Y~m;J_p
                                                                    c^t.c:0\q      f$n)     wfh)a          ~$X@i  ).x.).x.).  Bu$J$)O  .u'(  X$]   .n.(.n.|.n.|.  rn$C$u$C$v$Q$(  /.c`/.c  i$0$c$|    (r$O$z$O$X$Z$Y$Z$Y$Z$X$Z$t        Y"f.z"t.c`/.c           n'\.v`/.z^f.X"f.Y'  U:r.C. .$va)@x*($n#|$uW/
                                                                    .[.i.r:0]1     Q}hI:     \.             "m~L   :._.;._.I  +q(*+X.  l.?  >W-|  .l.?.  -.I.?.   lq(#-p|#?d\W]{  .!.].l  .p/&]b+     lkt8[kt8{hf%{ajB{aj%{hf8{d.  >.?   {.>.}.>.].i.]          .[.!.].>.}.>.}.<.]  .).+.  ]?p,Y<Z,Y~m:J_qlL
                                                                    {.r.f"X_o{n    {#($/{    ,$nW\*           c+n  .[.t.[.t. .$z&t$-  t.{  ^%f$   f.}.   .j.{.   .L!c"w-O-Bv8x$  .r.1.   i$U@x$Y     {$J@x$U@x$C$n$C$u$C$u$C$u$L$>  1.u   r.} j.).r.1.j         {.j.1.r.).x.(.n.|.  \.v`/  Ih[#(q-#|d?W/b[8f
                                                                    .;.-.c. .x_t   -lJ_ql]    ^dlL-c        ._.{.   .`.>.^.< {{hi0~-  .>.  d~O.  ,.<.,  .:.                         .   .m)a~m){    ^w)*+w)*+w(*_w|#-p|M-p|M-p|#-p<   .-. .-.  i.:.~.:.<        .:.~.:.+.;.+.I.-.;  .!.].  /"v:J.x;J.nIL'v!0
                                                                                    n(Mt$?     f$X8f*         u^0'  r.(.x.(. -$x$Cw  .\.  &v$r   '|.v   v`\.   'w_n   XiM/a|$r        tj$L$v$LX   (f$Q$c$Q$c$0$z$0$z$O$z$O$z$O$X$Z$|   .z^t.v    '\.u'\.x       v'\.v'\.v`/.c^t.X^  c:j.Y  I$jd]W\d]&tb}%fh1
                                                                        .                  !^  !}o<Z{J         I.\   _.I.-.l )+p|b. .].  0?p1{  .].l   !.?.   .1.  i:Clq|M?p\0  .?   v?d\M?d(}   n-b/W]bt&[b/&[bt8}kt8}hf8}kt8}hf8[a]   .}.>.     .!.?.l.       .? I.?.!.].!.[.>.{  .{.~.  t_0'ulC.viQ`c>O,U
                                                                     .                          )|$ua-o      ~J  .O   f.}.f. .$Y#.  1.  Or$zJ  .).t   x.)   1'X  '&cBx$X%f$X&.  {   aj$YBj$c[  .&n$YBr$U@x$U@r$J$x$J$x$J$x$J$x$J$tz wt   .n.1.     .{.j.{.      1.  }.j.1.r.).n.(.   .v'|  ]b+h{O>k}Z~a)q_#\
                                                                              .|                   x.I        ?p. .f   <.".~  ]b.  +.  n+Z}C  .+.    ,.~   /.  fim1h~Z{h<Z{h.     :  C)hiQ!   .U.rlQ^Y-b>O{o+w(#-q(*_w)*+w)*+w(*_ql   .  `._.:      .,.<.,.      ,  .:.~.:.+.;._.I   l.?.  X.j^z./`c.t"Y.r;J
                                                                         `Uld]Q                       J{b     /j$J&\*  .u.|.  o>  t.  Qr$C&  .f.    u^)  ~J,n`ou$C$n$L$tot$}    pcp                          !0{$Q$c$0$c$0$c$Q$c$0$,      \.c`       `|.u'|      .   `|.u'/.c^t.z"   "f.v  -%(m~a1Z~o1w-M\b}
                                                                       }^v.\^z.                          x![   l]*_q(X  .[.>  .  ?   0[d/#.  [     l.  ((Y.X(&]p|#-p|#_C                                    .Q.].X-b/&[b/&[b/8}b/&}w. .>.}.i.]        .!.?.          ?.!.?.i.[.>.}.  [.~.  u<J.f"z.f,X.r;J.v
                                                                      t_Y:m_wtt                             j.    pc8fb  .j.    ]  .Mr$Y%^     ;  t  .$YM}$z%r$Y8fM;                                         ^$C$x$U@r$U@r$U@x$J@x$Jb  .).x.).         .{.j          .j.{.r.).x.(.f  .n.}  {miw-CIq_JIq?Qib}
                                                                    ._ ~.x}&1J                                   ;  .O1Z  .-.     .h~Z1a.    u.    t>w1a~m{a<L"   .j.                                            j}*_w)o+w)*+q(#_w1h_\ i.;._.;.         .".          ,.~.,.+.:.+.;.  ".-. .X./.n.).j.).u.\`z
                                                                  )!d-L?$d$0$+         :                          qu$C$v$       uX$v$Q$.  Ou$    ?$v$L$u$Q$x*,Lj$?                                    u-0           8Q$c$Q$c$0$z$O&  cz n^t.c`|          '|          '\.u'/.x  .z"\   f.  t-o{Qld?Cld]Q>h{Z+
                                                                  .\.U_Mu$\&r?        ;@?                X.    ?)Y.f(#-p\W.    l|&?d\W]pf8!l   c\W]d\W]d\W?p\&I                                        fiO'_           n/&[b/&[b/8[j     }.i.].           .          ?.l.?.!   i.[.   .>  .x:z.\'u.(.u./`c.j
                                                                  C+az$m$Y$w8                            ,a-    nj$XBf$XW^      Qj$YBr$Ua   c|$Y@x$YBj$YBj$Uk           x^                             Im+o|q.            mu@r$U@r$z      n.).r.                     .j.1.r.   .(.x   n.  z]LIm~Y,0>z^0<Y:w-
                                                                  .p[ajB1arB^                            Y]Y.(   ;-h<O`  :;k~x   u)o+m[z.r[a~m1o+m1o+m1a~Z~>  .       'z.;        l$(1                 ]>X:U.x.           . .01o+wI|.     .+.;.+                     ,.~.,.<   +.I.   ._  .u.{./.]./.].t.1.n
                                                                  (J$d$L$d$0@                            U$U@\@x*  \$JBr$L$v$Q$|U hv$L$u$Q$v$Q$v$Q$v$Q$v$cL}$(      %|d\$.        dw$                  .$*$n8/d[0         uv$Q$v$0@.      t.z^/.u                    '\.u'/.  |.c`t.  \.  J~k]Y:q~Y:m~Y;q-Li
                                                                    n$\Mv$/&]                  i.|.\.    Mr%z8_d\*:Y(M?p|M?d\W]hta~p/W]b/W]b/&[b/&]b/W]b/&]C. .t  'd(b(@x-                              t$r$Y8Ic>c          [&]b/W]t       I.[.i.?          .        ].i.].   .i.[.I  .l  .r^v.|.f.[.t.{.r.(
                                                                     v$Z$Y$w%                .$d$L$p$rQ )n$d$C$z%j$Y%j$X%j$Y%r$U@r$YBr$U@x$U@x$U@r$UBr$YBrB_O(h.Ct$Y$L$b$.                              W0$k$O$Yp-q          >$J@r$u         .x.)./                  .r.).r   x.).x.   .  O<z^Lln.Y;x.UIu.Li
                                                                     ;fB1ar@}i      .:       zn$|Mu$|Mu@1#u$\o{b>Z{a~Z1a~m1o+m1o_w)o_w)*_w)*_w)*_w)*+w)*+w1a+0~d~m1h{Wv${!                              ;&c$/&z$+vI)          "*+m1*.          i.:.       .>        .:.+.;.   ._.;.+      .{.].|.~.}.~.)._.\
                                                           .       >a #O$b$0$j      r:r.     -$O$h$Z$a$O$a$m$Z$n$L$v$L$v$Q$v$Q$c$0$c$0$c$0$c$0$c$0$c$0$c$0$v$L$c$Q$u$o$w$!                      n       $*$w$*$q$zk+      QX$' |$Q$c$[               I*n$0$v$C#;    v`/.c`(  ./.v'/.      u'O<c'LIx.CIx'Qiz"
                                                           i.     .C[b+Mv$/Wz$.      {.x<c.>.C1BX$j%X$jBY$jBvM-p\W]d\W]b/W]b/&[bt&[bt&[bt&[bt&[bt&[b/&[bt&[b/W]d/W]du$r@zu      .              ;.}     lx$r@U$n$U&;t      _k/Z.n/W]d/k             ){&]p|W]O;f.(_w   ].i.]   ?.!.[.i      .+./.-.).+.)._.\.[
                                                            |.    Xf*($Y$U$w$J$       u-Mu$J$z$Y$J$b$Q$d$L$q$j$X%r$YBr$YBr$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@r$U@r$Y$Q$k$-     `/.          \`w+v.     i$O$b$Q$k$z%I     )$UBj$cBr$U$(            %YBr$YWl       ~$\  f.).   .r.).r.}    .x./.v'\.u.\.v`/.Y:
                                                            .;.    QIC_qidr@1*xm        .|!qlc.   ._.cn$\Wv%+m1a~m1o+m1o+w)*_w)*_w)*_w)*_q(*_q)*_w)*_w)*_w)*+m1o+m1a+*c$fZ     }.<.~       #j&c$|h-x   X/8z$t&c$/o+~    ;w)o~m1o~m)o_n          .C1a<m}f   ).].{  ?M;  i.,   :._.;.+.    `.~.!.-.;._.;.?.i.}
                                                             "t.   .$z8t$Y$L$b$Z$`         .         t$m$o$z$L$u$Q$v$Q$v$Q$c$0$c$0$c$0$c$0$z$0$c$0$c$0$c$0$c$Q$v$0$v$m$w$hJ     Lic"O'    vJ$*$w$o$q$Xdz$#$q$*$w$hk  "C/$0$z$0$v$Q$v$)         .$L$v$(   ~J;m~Y:L Uc$f  x.  x^/.c^/.v    .\.c,f.z`\.c`t.X,x.
                                                             ].>.{   q<O}k<qr$/Wz$_                 1$r@U$}d\W]b/W]b/&[b/&[bt&[bt&[bt8}kt8}kt8}kt8}kt8[bt&[b/&[b/&[b/&/$J$(~    .j.|1%,/.j.qU$x@J$x@J$x$J$n$J$x$J@. ~&}b_|   />b\W]d/x         0/M]U  .  1.1.j.1.j.ZtM.     .].i.[.i.    ?.l.}.!.?.l.].i.{.+
                                                              u.|.c!} #u#($nMj$m$J$pW.            $b$Q$p$x$YBr$YBr$Y@x$U@x$U@x$U@x$U$x$J$x$J$x$J$x$J$x$U@x$U@x$U@x$J@r$d$0$Q{     CiL/$O$u$c&z$h$0$b$0$k$O$k$0$k$C$Y$fa   J  . 1@r$UB.        BU@fO \j$cx  Ic`L!v'OjBx$.    1.r.).x.).  vlp-J;0!v.U,j.c"j.c`
                                                              ._.l.uIY~q;C?p!L?a_L1B\Wv8:1.  ;`o(Wv$\MjM~m1a~w)o+w)o+w)o+w)*_w)*_q(*_q(*_q(*_q(*_q(*_q(*_w)*_w)*_w)*+w)&|8X${!     >.{^C`n^j.:.|.r]@t&c$t&c$t8c$(d)o'        C. .m)o<        c)#~] \<w1a<v   +./.].L+w})    .;.+.:._.,  .viL'uIU.r,Y.xIL^z>Q
                                                               .Y,x~$c8t$X%f$YBx$!   !Cio|b{$v&/$O$L$0$v$L$v$Q$v$0$c$0$c$Q$c$0$c$0$z$0$z$0$z$0$z$0$z$0$z$0$c$0$c$0$c$0$c$d$p$hY       |.z.        uQ$*$w$*$w$#$J$0$[ "C O0$j .@- ?$c$       B0$cB ux$0$u$L$}   .0~U1$L$i    c`/.c`/.c'  Ofh}%jd[8\q?W\b{$v%x
                                                                .1.\]k>O{h~Z{a~m)*.         .j.U[M?d|M?d\M?d/&[bt&[bt&[bt&[bt&[bt8}kt8}kt8}kt8}kt8}kt8}kt8}kt&[bt&[bt&[b/W1&U$vk                .$x$J$n@J$x$J$[b/&~! Y. ?&]d> .p^ .q-      r/W]kI .(:m>q\W]b\*,].x.O\W]j    .[.i.[.i.[  .Q:z<m`c>Q.uiQ`Y-b~w
                                                                 .via($uM\$uM\$c&t$x&f$tMf$X%f$X%j$X%j$YBr$U@x$U@x$U@x$U@r$U@x$U@x$U$x$J$x$J$x$J$x$J$x$J$x$J@x$U@x$U@x$U@x$J$J$k$Q$^         .$k$0$k$O$k$0$m$r$U8[m  +X *r$Y%I )$< lQ     aU@r$Uq  .}    ;@Y@r$UBr$YBr$!    1.x.).x.).f  ?$nb]o)p+a1m+* a($c
                                                                 ^.(^J_qlL?d!Q]diQ[bi0[bi0[h<Z{a~Z1a~m1o+m1o+w)*_w)*_w)*_w)*_q(*_w)*_q(*_q(*_q(*_q(*_q(*_q(*_q(*_w)*_w)*+w)*+m)8|WnW]av$/Mv$r%Y$f8z$t8X$)d(*+w1q.{.  r' .w)o+J  ,w;      \)o+m1k`" ].[.t.  _Im1a~m1o~m[-    .:.+.;.+.:.  |?m^c;U.j"X.r:J'X-p
                                                x                  .8X%f$Y%j$YBr$U@x$J@x$J$n$C$u$L$v$L$v$Q$v$0$c$0$c$0$c$0$c$0$c$0$c$0$z$0$z$0$z$0$z$0$z$0$z$0$z$0$c$0$c$0$c$0$c$Q$\0                t$z$Z$v$Q@_p?Y  ?Wi ;$z$Qb  rBl    h0$v$um;w+U;q_U;w_v  f$v$Q$v$L#     n'\.v`t.c`/  >%t$rd]&|w-M\d[%u8j
                                                 _           ?.     Ia<0{a<Z1o~m)*+w)*+q(*_q|M-d\M]d\W]d\W]b/&[bt&[bt&[bt&[b{U?bt&[bt8}kt8}kt8}kt8}kt8}kt8}kt8}kt&[bt&[bt&[bf8[k/&[b/W+X<k!c.-  >X.1[&++   i)8it'u.  /'p(\ )1o<z ]>d`  |/W?mln.(.x.).x.).x.[  ,d\M?d/M.      ?. .].i.[.I _lZ_w`v!C.nlL'z~q!0
                                                 .t.[         u'\    ]$uM\$vW\$vW/$c&/$z8t$z%f$Y%j$YBr$YBr$U@x$U@x$U@x$U@r$YU.$J@x$U$x$J$x$J$x$J$x$J$x$J$x$J$x$J$x$U@x$U@x$U@x$C@x$U@r$J$x$J$r$u8r$U$/j Lr$\ .b~Y:m. .m\@x$YBr$Y0 nv@^ ]$j$Yw  ;X^0ic^0ic`Qi|  j%j$YB\n      .r  .x.).x.  kxk[o{Z<k}Z<h{q}Br
                                                  .i."        .?.!.~  .qlL?d!L?di0[b>0[k>0}h<Z{a~m1a~m1a~m1o+m1o+w)*+w)*_q1C.I(#_w)o+w)o_w)*_q(*_q(*_q(*_q(*_q(*_w)*_w)*_w)*_w)*_w)*+w)*+w)*+w)*+w)o_f   z)*_u  .).|  .n;m1a+m1o~r ?!w" .w)o_Z. .?./.]./.].t.  C~Z{a~t       ,.   .~.:.+  .Q`c:Y.f`c.t^z.c~m
                                                   .n.|.       .X,x.J_v nrBr$YBr$U@x$J$x$J$u$L$v$Q$v$L$v$Q$v$Q$v$0$c$Q$c$0o.u"$X$0$c$0$c$0$z$0$z$0$z$0$z$0$z$0$z$0$z$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$? .  rj$Q$[   :0  ^hc$v$Q$c$Q*.LY$fz q\$L$. :U;w+U:m+U;m  ?$L$u$        '\   /.v`/.x  :8rp?M(m+#(w-WrM\
                                                      .!.?     :.1.~.nlQ>m>Z1o~m)o_w)*+q(*_q|M?d\M]d\W]d\W]b/W]b/&[b/&[kt8^ .(\Bz@}b/&]bt&[bt&[kt8}kt8}kt8}kt&[bt&}kt&[bt&[bt&[bt&[bt&[b/&[bt&[bt&]b/U I'f   tId|m.     .XIb\W]d/W[L ?~k/z       j.).r.).r.1.  z\M?q.        _.:  .!.].!.  ~>w.uIY.r;U.x!ZIJ
                                                          t.     .u'/.*nM|$uW\$vW/$c&/$z8t$z%f$Y%j$YBr$YBr$U@r$U@x$U@x$U@n%  ,$p$v$U@x$U@x$U@x$J$x$J$x$J$x$J$x$U@x$J@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U%+  n:m~c.z]Mf$cm.   .Z1&r$Y@r$J* Xz@rd (^Q>z^0ic`Qic`Qi|  jBj$;  /       j.  t.{.j.1   0?a}Z>b]0id[m?&f
                                                     ".           .].>.wlL?d!Q]bi0[k>0[k>0[h<Z{a~Z1a~m1a~m1o+m1o+w)*+w1o_q}  j(#_w)o+w)o_w)*_w)*_w)*_w(*_q)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*+w)o<v.  ?.j.1'O~w(*+Z+)  .j.C1o+m1o+_.p_Z~>.[.t.[./.[./.].?  ,k~O.  "        .<   +.,.~.,  .Y:c.\.u.\.v.u!O
                                                      |.n.)     c"j.U:X)$Y%j$YBr$J@n$J$x$J$n$C$u$L$v$Q$v$Q$v$Q$v$0$c$Q$v$0$) t$c$0$c$0$c$0$c$0$c$0$c$0$z$0$c$0$c$0$c$0$c$Q$c$0$c$0$c$0$c$0$c$0$c$0$c$nO"  n!b]Li*v$v$Q$c$  :kn$v$Q$v$\rf$QB^ <J;w+U;m+U:m<   f$n$_  x.        (.   .u'\.v'  Urp>h}O~a1Z~Mfo(
                                                       I.-.l     {.~.1.j}a~Z{a~m)o+q(*_q(*_q|M-d\M?d\M]d\W]d\W]b/W]b/W]d/&[k[*]bt&[b/&[bt&[bt&[bt&[bt&[bt&[bt&[bt&[bt&[b/&[b/&[b/&[bt&[bt&[bt&[b/&[b/a.\.-  .x.\'n.C|W]btc ?"d]d/W]d\q.O\M_\ 1.).r.1.x.1.  ?{M?w.  I.-        .I   I.-.l.?.  C`nIU.r:Y.jlZ;J
                                                        }.j.1.   .u.\.vlb|$uM\$vW/$z8t$z8t$z%f$Y%j$Y%j$YBr$YBr$U@r$U@r$U@x$J@r$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@rB_X:Z^       ]8x$J@! "L($UBr$YB(Un@r$1  0>c`0!u.    *XBj$"  t.[.         .   .{.f.{.j  .W(q<k[Qlw?O-Wt
                                                         ".<.;.   .-.!.}.J?plC?d!Q]bi0[bi0[k>O{h<Z{a~Z1a~m1a~m1o+m1o+m1o+w1o+w)*+w)o+w)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*+w)*_w)o+m1w.).j.{.  ?.O~m1o+r }.L1a~Z1a+U.w+m1Q           j!Z}k<n   ".i.          i.   .".<.,.i  ,Y.t'u.(.r.xlQ
                                                         .(.u't   /.Y,r.wx%f$XBj$YBx$U@x$U@x$J$u$C$u$L$v$Q$v$Q$v$Q$v$Q$v$Q$v$Q$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$0$v$Q$v$Xh>d-1 Z]wj$Q$v$j .&C$v$L$v$r|/$Q$)  q<w<L-$Y$u$C$\Y   n.).x          .r   u.(.n.\.  z)%\m~a}Q>*./h1
                                                            .-.!   <.{.~.YiO}h~Z{a~m)*+w)*+w(*-p|M?d\M?d\W]d\W]d\W]d\W]b/W]b/W]b/W]b/&]b/W]b/W[b/&[bt&[bt&[bt&[bt&[bt&[bt&[bt&[bt&[bt&[bt&[b/&[b/W]b/W]b/&]X'j ;`c^p/W]b/d ~~#?d\W?d\C 0\M]L  .m\#-p|M-q|a.   .;._.;.          ;.   .-.I.-.l.  U-O.x:X.jIQ"U
                                                                   .|.u.\'MnM|$uM\$vW/$c&/$c8f$X%f$Y%j$Y%j$YBr$YBr$YBr$U@r$U@r$U@r$U@r$U@r$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@r$U@r$U@r$(Y. .YI8YBr$U$[ 'aj$YBj$YBI x@j$r]  ;#f$X8f$cC     t.[./.]           ]   ].t.[.t.{  ,p<p-J:Z~Q+#\
                                                                    .I.-.>.ZIC-plL?d!Q]bi0[kiO}k>0{h<Z{a~Z{a~m1a~m1a~m1a~m1o+m1o+m1o+m1o+m1o+m)o+m)*_w)*_w)*_w)*_w)*_w)*_w)*_w)*+m)o_w)*+w1o+w1o+w)o+w)o+w}U.  1.t?o+m1o+r }!m{a~m1a~- q+Z{m. . .L{k>J.       .i.`.i.           .    ^.i.^.<."  .f.x.1.x.r;C
                  (.n.|.c"f.Y;x.J;u.                                x"f.X,v-$X8f$YBr$YBx$J$x$J@x$J$u$C$u$L$u$Q$v$Q$v$Q$v$Q$v$Q$v$Q$v$Q$v$Q$v$Q$v$Q$c$0$c$0$c$0$c$0$c$0$c$0$c$0$c$Q$v$0$c$Q$v$Q$v$Q$v$Q$v$LW~m  ,bt$c$Q$c$) '$Q$v$Q$v$; r$C$fz Wl ]B|L         ).r.1.            r.   .).r.(.u'  x(Z>k[Q>o\b[
    .-.l.].!.].>.1._.|.?./.}.f.{.r.-                                 ?.>.{.}>k>Z{h~Z{a~m)*_q(*_q)*_q(#?p|M?d\M?d\W]d\W]d\W]d\W]d\W]d/W]b/W]b/W]b/W]b/W]b/W]b/W]b/W]b/W]b/W]b/W]b/W]b/W]b/W]b/W]b/W]b\W?Z+X.  [./!h?d\W]b/c (\W]d\W]d(].w\M-O. ~p.             .                 .+    .;._.I.-.  j.t^c./,C`z
                     .t.}.f.1.r.).u                                   x.|.u'v]$n#|$uM\$vW/$c&t$c&/$z&t$X%f$Y%j$Y%r$YBr$YBr$YBr$YBr$Y@r$U@r$U@r$UBr$U@r$U@r$U@r$U@r$U@r$U@r$U@r$U@r$U@r$U@r$YBr$U@r$U81k~|  :Y!&z@j$Y%j$U@. /$r$YBr$Y# CX%f$x| @zo            ./.]                     /.].t.[.f.  0<X,Z~L<*(
                                                                      ._.I.-.)<wIC-plC?d!Q]biQ[bi0[bi0}h>Z{h<Z{h~Z{a~Z{a~Z{a~m1a~m1a~m1a~m1a~m1a~m1a~m1a~m1o~m1o+m1a~m1o+m1a~m1o+m1o+m1o+m1o~m1a+w[0.1.  +.XIm)a~m1a~Z}o. .a<Z{a~m1a. ^h>Z}Z."-h<Y           `                        .i.^.>.".~   j.1.j.rIC
                                                                       .c"f.X;m|$z8f$X%j$YBr$U@x$U@x$U$x$J$u$C$u$L$u$L$u$L$u$Q$v$Q$v$Q$v$Q$v$Q$v$Q$v$Q$v$L$v$L$v$L$v$Q$v$Q$v$Q$v$Q$v$Q$v$L$v$Q$c$jQlQ  ^d/8v$Q$v$Q$u$L$; t$v$L$u$L$[ !@u$C$( .8n$Cp                                   ).r.).x.|.x  .d]Lia\h{
                                                                        .[.<.}.x]k>O{h<m1o~w)o+w1o+w)*_q(*-p|M-p\M?p|M?d\M?d\W]d\W]d\W?d\W]d\W]d\W]d\W]d\W?d\W]m1M]d/W]d\W]d/W]b/W]b/W]b\W?d\W?J^n.  \.x}M]d\W]d\W]d\*. +M]p\M?d|M. .b_p|#?Y [<q(#?c                                  .;.+.:._.l.+  .z.t:L^X
                                                                        }.n.(.u^O)$uM|$uM\$vW\$vW/$c&/$c&/$z8f$X%f$X%j$Y%j$Y%j$Y%j$Y%j$YBr$YBr$YBr$YBr$YBf$YBr$`{)$YBr$YBr$YBr$YBr$YBr$YBr$U%{q<X. `X;#c%j$YBr$Y%f$U*./t%j$Y%j$YB_ ;Mf$z%f$\['$c&t$cX                                 /  ./.].f.{.   ,q_Q+M/
                                                                         ;._.l.].x-qIC?plL?d!L]b!Q[bi0[bi0[k>O}h>Z{h<Z{a~Z{a~Z{a~Z{h~Z{a~m1a~Z{a~Z1a~m1a~Z{a~m. .Z{a~m1a~m{a~m1a~m1a~Z1a~Z{w.{.{ ^.j.J{a~m1a~m{a~m)J !_a~Z{h<O{a. .q<0[k<O[n f[bi0[bl^                                . .`   `.<.:.  ^.x.x!Q
                                                                          /.z,f.X;mt$c&t$z%j$YBr$U@x$U@x$U@x$J$x$vMn$C$u$C$u$C$u$C$u$L$u$L$u$C$u$L$v$Q$u$L$uo (($C$u$L$u$L$u$Q$v$L$u$X#}W(Old-  O-Q}$L$v$L$v$L$v$C0 0X$u$C$u$LB; ?$u$C$n$Ua Xz$x$U@j$t                                  r.)   ).u'/.  t>*th1
                                                                           i.}.<.1./]ki0[k>Z{a~m1o+m)*+w)*+w)*_w1U  .w+q(M-p|M-p|M-d\M?p|M-p|#-p\M?d\M?d\p. .Z_d\M?d|M?d\M-p\W?d\k"j'n.|.u.\.  (.J>p\W]d\W]d\M?d{| f)#-p|M?d|p.:~#_q|#?p(*. +#+m)o~m1h                                  .+.;    .?.i.  -:Q,L
                                                                            {.n.|.u'z[$x#($uM\$uM\$vW/$c&/$c&t$c8f$|U.bu8t$c%f$X%f$Y%f$n#{%jo|$XBj$v*~Y  .qx%j$X%f$X%f$X%f$X%/%)C"O>X"Z<X,Z"  0-bf$Y%j$Y%j$XBj$vt bXBj$X%f$cc Lu%f$z8t$c8:ft&/$v&/$uW|                                 .].t.[.   .r.(.  Lx$m
                                                                             ,.-.I.-.?IwIJ-qIC?plL]diQ[bi0[bi0[bi0}h<Z}ki0[k>Z{h<Z{h<Z]X.+.<.       .l.JlZ{a>O{h<O}h<O{h<O?0.).t.}.t.^      .['d~Z{a~Z{a~Z{h<Z][ r{a~Z{h+m~  n{h<O[k>0[k. ,kiQ?d!Q]bii                                 i.`.>.".    +.I.  CX$
                                                                              ).z"j.X,v_$c&f$c8f$YBr$U@r$U@x$U@x$U@x$U@x$J$x$J$x$J$x$J@n$C$u$J$n$C$n$C$u$C$x$J$x$C$n$U&{o[LIq_JI0.   .r^m-0+Wn$u$L$u$L$u$L$u$X/.$L$u$C$u$  !$L$n$J$n$J$> -Br$U@r$Y@\                                     .).x.|.    u^t.  oq
                                                                                .}.<.1._.m>O}k<Z{h~Z{o+m1o+m1*+w)*+w)*+w)*_q(*_q(*_w(*_w(*_q|&1a\#-p|M_w(#_q(*_w(o<J;v.(.n.|.\   +.(,C:01o_p|M-p\M?d\M?d\M?p\C.Z|#-q|M+) }ib|#_w)#-q(#. .o_m1o+m1a.                                      +.;._.l.     .~.  U
 .j. .n.}.j.}./.(.f.).t.1./. .f.[                                                .n.|.u'/^#x#($nM|$u#|$vW\$vW/$c&/$c&/$c&/$c&/$c&/$c&t$z8t$z%u$Z@f$c&/$z8t$z8t$jwlOic^Q>z^J.   ,J~8u8f$X%f$X%j$X%f$X%f$X%j$X%t$z%f$z%1j Zf$c&t$c&f$z&I ~W/$vW\$vw                                       ].t.}.f.1  !X  .\.  
.{.f.1'u.1.n.).n.{.x.|.n.\.x.|.n.                                                  -.l.?.!.c,C_qlC-plL]d!Q]bi0[bi0[bi0[bi0[bi0[bi0[b>0[k>0[k>O{h>O[bi0[k>0[q`t.t.[.f.].+    .}^O!O[k<O{h<O}h<Z{h<Z{h<Z{hiO}h<Z}h<O{h. .Q>0}k>0[bi0[k. .biQ]b!L~}                                      .  `.>.,.~." i+q.  I.>
$X%f$YBr$U%t$Y@x$X8f$U@r$X8t$c&f#                                                    "f.Y,r.pr&/$z8f$z8f$X%j$YBr$U@r$U@x$U@x$U@x$U@x$U@x$U@x$J$n$J$n$J$x$jmlw+U;w>j      "U+BX$n$J$x$C$u$C$n$C$u$C$n$U*~av$u$C$u$C$~ i8n$J$x$U@x$U@? _%x$YBr$1                                        B?  |.n.\.v`  aa$nz  .
Y$x@U$x@U$f#n$n$J$t%J$xBX$\8z$t&:                                                      >.{.~.\.L}k>0[k>0}h~Z{a~m1o+m1*+w)*+m)*+w)*+w)*+w)*+w(*_q(*_q1k,j.j.).[     l.x.riq<q|#-p(*_q(#-p|#-p|#-p|M-q[J.):k-q|#-p|#i-.h_w(*_w)*_w)*^ .k~m1a<u                                          }$`  l.?.!.[. .@n$JM. 
$d$W$d$W$d$M$d$W$d$W$d$W$Z$W$d$af                                             o          .u'\.cIm1$x#($x*($nM\$uM\$vW/$vW/$v&/$c&/$c&/$c&/$c8t$c&\@)U^0!n.     `u:d{k($z8f$c&t$z8t$z8t$z8t$z8t$z8f$xQ^0-at$z8t$z8t$\ot$z8t$c&t$c&? .a\$u&{j                                           $W$. .1.r.).r  )$a$p$Z
v$Q$v$Q$v$Q$v$Q$v$J$v$Q$v$Q$v$Q#                                             l/<           ?.i.].}!wIJ_q;J-plL?plQ]d!Q]biQ]bi0[bi0[bi0[bi0[b>O[q.|.|.I    .(.1`L;Q[k>0}k>O[k>0[k>0[k>0[k>0[k>0[k>Z{b"v~d>O}h>O[k>0}k>0}k>0[bi0[k"I.C!L?m.  i.:                                        }$vm  .,.+.I.  ]r$r$Q$
$B$o$B$o$B$o$B$o$B$o$B$o$B$o$B$"                                             +$-             :r.U;v~$c8t$z&f$X%j$YBj$YBr$YBr$YBj$U@r$Y@r$U@r$xwIO;    /`Z+Q-$Y@x$U@x$U@x$U@x$U@x$J$x$J$x$J$x$J$n$J$x$J$x$J$x$J$n$U&\$z@x$U@r$U@)r kj$zX    .J"                                    1.  @o$B0  '\.c"f.  %w$%$o
m$Y$m$Y$m$Y$m$Y$m$Y$m$Y$m$Y$m$[                                              Otp               +.)._.X:Q}k>0[h<O{a~Z{a~m1a~m1a~m)o+m1o+m1h;x.j.    ].x.t<b+w)*_w(o+w)*+w)*+w)*+w)*_q(*_q(*+w(*_w(*_q(*_q(*+w)*_Z>c.{.Uim)o+m1*:I m_L.      l.{                                    .;  <$m$v; ?.!.[.<  .&J$Y$
$d$W$d$W$d$W$d$W$d$W$d$W$d$W$qc                                              t$C}                .c^t.Y~p)$n#($x*|$uM\$uM\$nM\$vW\$vM\$xw,L;{   j'0_m1$c8t$c&/$c&/$c&/$c&/$c&/$c&/$c&/$c&/$c8t$c&/$c&/$c&/$c&/#~u'Li0)$vW\$vW1r q1U        ./.j                                   /.  %W$d$C  x.(.n'{ xL$d$W
v$Q$v$Q$v$Q$v$Q$v$Q$v$Q$v$Q$vU                                              .q/#.          [./`(   ?.>.[.{lwlC_qIC-plL?plC-dIC?p!Q?blc./.!   i./.n_di0[ki0[bi0[b!Q[bi0[bi0[bi0[bi0[bi0[bi0[b>0[bi0[bi0[bi0[biJ'/.?.UlQ]b!L]dI_ z.           .`                                    .i  >$v$Q$. ._.I.?.  dx$Q$
$B$o$B$o$B$o$B$o$B$o$B$o$B$o$                                               oQ@xa         z<h{m+o?   'n.JIx,Mu%t$z8t$z8f$z%f$X%f$X%(k<v   r"Z]k/$YBr$Y@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@x$U@r$XBr$U@r$X%j$t\                  .                                ).  ho$B$o$  .X"j.Y  _$B$o
U$j%z$[kjB{arB1an$(MC$u$J$x@.                                               ?*~Zl        r.f"X. .Y.r.   .|._.\.J}k>0}k>0}h<Z{h<Z{q.{.  :.f.n?o+m1a~m)o+w)*+w)*+w)*+w)*+w)*+w)*+w)*+w)*+w)*+w)*+w)*+w)*+w)*+w)o+m)o+m1o~m1o+C.  l.]    .i.].l.?.I.0lL-)                            .I  .$m$Y$Zu !.{.~.- ?X$Y$
$d$W$d$W$d$W$d$W$d$W$d$W$d$j                                               "&/$nb       YIq?Llv t!b[0i0   n,f.X"v+@n#($u#($n#($jQ.   .JIU[$vM\$vW\$vW/$vW/$vW/$c&/$c&/$c&/$c&/$c&/$c&/$c&/$c&/$c&/$c&/$vW/$vW\$vW\$vM\$v8~   .x.).r.1.r.{.j.}.f^Q[8fp                             f.  QW$d$W$Y  \.v`/. '$d$W
v$Q$v$Q$v$Q$v$Q$v$X$v$Q$v$-       .$v                                      Y.+        .n.).n.|.  (^v.\'c.>   ~.{.<.z:C_q;J-qIUI/   [.]^m!L?dlL?d!Q]biQ]biQ]biQ[bi0[bi0[bi0[bi0[bi0[bi0[bi0[bi0[bi0[bi0]biQ]biL]d!L?d!L~(   -.;.+.:.~.:.+.,.<.:.J"z>O.                             .~  .$v$Q$v$. .!.].I i{$Q$
$B$o$B$o$B$o$B$o$B$a$B$o$\       )$o$,                                               ?Oid]0ik}w'  m+a)m~o1w!    Uln.Z)/$c8t$}x  .z:*u%j$X%j$XBj$YBr$YBr$Y@r$U@r$U@r$U@r$U@r$U@x$U@x$U@x$U@x$U@r$U@r$U@r$U@r$YBr$YB1Y     /.X`/.c`/.c`/.v.|.X[o)@x#)                  p{k<j.      1.r |k$B$o$%M r:r.U,  $B$o
m$Y$m$Y$m$Y$m$Y$m$Y$m$Y$.       c$Y$mZ                                             <^c./'v./^c.j.  \:Y.j:U.I       _.|.t+b<z.   .x'L}k>O1a~Z{a~m1o~m1a~m1a+m1o+m1o+m1o+m1o+m1*+w)*+w)*+w)*+w)*+m1o+m1o+m)o~m1a~w[X        .i.].i.[.i.].!.-.}iw;J_qIc                  .L?dlL]dIU"|     $m$Y$m$j  {.~.)  1$Y$
$d$W$d$W$d$W$d$W$d$W$d$.      %W$d$W$X                                            Q+U:m+U:m+U;q-Q^  }lb]C.   .z^t.    r,r'0:   ;Y[$u*($nM\$uM|$uM\$vW\$vW\$vW\$vW\$vW/$vW/$vW/$vW/$vW/$vW/$vW/$vW\$vW\$uM\$uW\h     {.    x.(.r.1.r.1.j.{.k/b[&tb[8i                  jjo{%jo1Bro1@fO. .$d$W$d$: .v`/.  ad$W
u$J$x%C$v$Q$v$Q$v$v$\(      .#J$f&c$fW.                                          ].r.1.r.1.x.).u.\._  .f   -.>.[.>.?      .   .v:C_q;J_qIC?plC?d!L?d!Q]d!Q]d!Q]d!Q]d!Q]biQ]biQ]biQ]biQ]biQ]biQ]d!Q]d!L?p!Q_z   (.~  .I    ._.;.+.:.+.,.-.u>0^ci0^ci                    Q:X<Z,U+w:Y!U.t`)  t$v$QJ `.[.i  '$L$
$B$o$B$o$B$o$B$o$B$)      Jq$B$o$8$o$pt                                         O[Q!d]Qib]Qik[0>h}Z~q    'x.U:r.U;x.c  .n   x>m\$z8f$z8f$X%f$X%f$X%j$YBj$YBr$YBr$YBr$YBr$YBr$YBr$YBj$YBr$YBj$Y%j$YBj$U@/p   L(b]o   c^)   /.c`\.v'/.u`U[@x*)@x*($xZ                .   _$vM/$xJ           $o$B$u  x.U;| %B$k
m$Y$m$Y$m$Y$m$Y$m#      `$Y$m$Y$Z$;>                                           ?`v.\'v./^c.t^z.f"z.f,z.   ._.1.+.(.-.  ;.?  .c!O[kiO{h<Z{h<Z{h<Z{h<Z{a~Z{a~m1a~m1a~m1a~m1a~m1a~m1a~m1a~m1o~Z{a~Z{h~Z_j  .n.v!Q`v^  I.]    .i.].!.?.!.U;J_qIJ_qIC-m                 :   ]]d^[  .z(M`  -.-.nc$m$Y&  ._.(. ~$Y$
$Z$h$0$#$p$o$q$x      QY$Q$k$J$>                                              j<Y,m~Y:m+U;w_JIw_U;q-Clp-/  ./.v`/.z"t   /  'n_$x*)@n#|$uM|$x*($uM|$uM|$uM\$uW\$uM\$uM\$uM\$vM\$vM\$uM\$uM\$uM\$v*>r   L}w~a1m<o1u  .(.    x.).r.{.c+p}8th}8tk}8th;        c   /   /.]   t  !#z$w$U$Zq  .]?$W$d$a| u^/.j dd$o
v$Q$v$Q$v$Q$rY                                                                .j.{.r.1.x.(.n.(.x.).n.|.u.(.  ".[.>.[.   .  {.X+w;U+qIC?plC-q;J_plC-plC?dlL?plL?dlL?dlL?dlC-dlC-plL?plL?p!L?d!Y.   .r.x:U.r:Y.j"c.  _.,    .+.:.~.{IO"z<O"X<O"z<O`    `   n"   .  `.i.`  .Jt@)ox@)*r@|w.  oQ$v$Q$. .[.>  "$Q$
$B$o$B$o$B$-     .|.v'|.x.X-*1w`                                             ;Q!d?L!b]Q>k[0>k}O>k}O>h}O<h{mi   .J;x.U.    ).duW/$vW/$c&/$c&t$z8f$z8f$X%j$X%j$X%f$XBj$X%f$z8f$z8f$z&t$z&t$z*ix ),*\d?W\d?M|d?M\dl  |.c    ./.v`t:&n#($n#|$n#|$u#|q   r   *no.  1.r.).x.  *b$L$b$0$k$0$h$1Xx$o$%$b$  .J;  $B$o
#include<iostream>
using namespace std;

int main(){

    string str;

    getline(cin,str);

    for(int i=0;i<str.size();i++){

        if(i==0){

            for(int k=1;k<50;k++){

                if(k>str.size()){break;}

                if(k%2 == 0){str[i+k-1]=str[i+k-1]-'a'+'A';}

                if(str[i+k]==' '){break;}

            }

        }
        if(str[i]==' '){

            for(int m=1;m<50;m++){

                if(m+i>str.size()){break;}

                if( m%2 == 0 ){str[i+m-1] = str[i+m-1]-'a'+'A';}

                if(str[m+i] == ' '){break;}

            }
        }

    }

    for( int n = 0; n < str.size() ; n++ ){

        cout<<str[n];

    }

    return 0;
}
